version: '3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - static:/vol/web/static
      - media:/vol/web/media
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=False
      - SECRET_KEY="&_)63=9%r$fz1-79x!f2m96e5$lh=no6yfphp_j5(_pdprfqz@"
      - DEFAULT_FROM_EMAIL=divinehycenth@outlook.com
      - NOTIFY_EMAIL=divinehycenth@outlook.com
      - STRIPE_PUBLIC_KEY=pk_test_Q9naIgB4oHQ5nMDjx4vGki8T00ikLRj9oy
      - STRIPE_SECRET_KEY=sk_test_51GaLOrGXbsQDHOUXuue71uGfNRZxWy0UBioGygbDONzdoDiJJuhbxT5XjjEsigllZBlx2QSUcoJGNoJKqJZi7nou00leAp56PL
      - PAYPAL_SANDBOX_CLIENT_ID=AS1HJ4zzeXbFRlJOXmznq7seOe1ckhPf_DN99CVU4Q15yV4ar1emr3HCQ5brpMnN6RiAUS3HEQI6SboZ
      - PAYPAL_SANDBOX_SECRET_KEY=EPfKcB-6R4mMyHsgQk8KEwuyZpq6bUe7MJySYvcf2vhXG35QSY1w6TBSm3l9U5BakjpbTYLF4Gy1vRyr
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword

    depends_on:
      - db

  db:
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
    # volumes:
    #   - .:/app

volumes:
  static:
  media:
