version: '3'

networks:
  ecom:

services:
  app:
    build: .
    networks:
      - ecom
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - static:/vol/web/static
      - media:/vol/web/media
    command: >
      sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    env_file:
      - .env
    depends_on:
      - db
      - smtp

  db:
    image: postgres:12.5-alpine
    networks:
      - ecom
    env_file:
      - db.env
    volumes:
      - dbpostgres:/data/postgres

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    networks:
      - ecom
    depends_on:
      - app

  smtp:
    image: namshi/smtp:latest
    expose:
      - 25
    ports:
      - 25:25
    env_file:
      - smtp.env
    container_name: ecom_smtp_gmail
    networks:
      - ecom

volumes:
  app:
  dbpostgres:
  static:
  media:
