version: '3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    # command: python server/manage.py runserver

    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USeR=postgres
      - DB_PASS=postgres
    depends_on:
      - db

  db:
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USEER=postgres
      - POSTGRES_PASSWORD=postgres
